# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "CatsAndModules")
  end
end

lane :build_and_export do
    gym(
        configuration: "Release"
    )
    
    release_notes = "Some notes"

    firebase_app_distribution(
        app: "1:582683036276:ios:3ea4fc2550574f52c29f21",
        firebase_cli_token: "1//0ciJWqGQL8o98CgYIARAAGAwSNgF-L9Irs7_LfC8fexPNiTSgCGGxDLbox-TKqYf-uBqxWx_w009LbesKroim-HQDTArugUCyNA",
        release_notes: release_notes,
        testers: "o.frankiv@ukma.edu.ua"
    )
end

lane :take_screenshots do
    snapshot()
end
